// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7wMQ_z1bj7Hnl9zNEADCwPlvnd29oJp0',
    appId: '1:937792262665:web:32d9d6c00b9ea368cdded8',
    messagingSenderId: '937792262665',
    projectId: 'fir-app-10500',
    authDomain: 'fir-app-10500.firebaseapp.com',
    storageBucket: 'fir-app-10500.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhG2MJR211HKrmRz74sQyx7dqkxxYpv2A',
    appId: '1:937792262665:android:4cc987d074391a29cdded8',
    messagingSenderId: '937792262665',
    projectId: 'fir-app-10500',
    storageBucket: 'fir-app-10500.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjAW4Er2ZbjF7wjy2H8DBHzXaXatclfw',
    appId: '1:937792262665:ios:29fa9258646ba3aecdded8',
    messagingSenderId: '937792262665',
    projectId: 'fir-app-10500',
    storageBucket: 'fir-app-10500.appspot.com',
    iosBundleId: 'com.example.flutterBasicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjAW4Er2ZbjF7wjy2H8DBHzXaXatclfw',
    appId: '1:937792262665:ios:0148adf7c8f99609cdded8',
    messagingSenderId: '937792262665',
    projectId: 'fir-app-10500',
    storageBucket: 'fir-app-10500.appspot.com',
    iosBundleId: 'com.example.flutterBasicApp.RunnerTests',
  );
}
